# Generated by Django 3.0.8 on 2020-09-25 17:10

import api.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('name', models.CharField(max_length=20, primary_key='TRUE', serialize=False)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('house', models.PositiveIntegerField(default=0, unique='TRUE')),
                ('price', models.IntegerField(default=10000)),
                ('seat', models.IntegerField(default=100, null='TRUE')),
                ('actor', models.ManyToManyField(to='api.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.TextField(max_length=20)),
                ('des', models.TextField(max_length=1000)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('written_date', models.DateField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField(default=5, validators=[api.validators.validate_score])),
                ('count', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.Movie')),
            ],
        ),
    ]
