# Generated by Django 3.0.8 on 2020-10-03 03:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=20)),
                ('synopsis', models.TextField()),
                ('published_date', models.DateField(auto_now=True)),
                ('running_time', models.IntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='api.Actor')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('container', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('startTime', models.DateField(auto_now=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15, verbose_name='user nickname')),
                ('movie', models.ManyToManyField(blank=True, related_name='movies', to='api.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('written_date', models.DateField(auto_now=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.Profile')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'managed': True,
            },
        ),
    ]
