# Generated by Django 3.0.8 on 2020-09-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='historyId',
            new_name='history_id',
        ),
        migrations.RenameField(
            model_name='mytraining',
            old_name='myTrainingId',
            new_name='my_training_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='deviceUid',
            new_name='device_uid',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='routineId',
            new_name='routine_id',
        ),
    ]
