# Generated by Django 3.0.8 on 2020-09-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('office_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='professor',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contact'),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Contact'),
        ),
    ]
