# Generated by Django 3.0.8 on 2020-10-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='seat_left',
        ),
    ]
