# Generated by Django 3.0.8 on 2020-09-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200926_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firebaseUid',
            new_name='firebase_uid',
        ),
    ]
