# Generated by Django 3.0.8 on 2020-09-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200926_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(default=-1)),
                ('is_done', models.BooleanField(default=False)),
                ('val1', models.IntegerField(blank=True, null=True)),
                ('val2', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('memo', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='normal', max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='mytraining',
            name='profile',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='routine_id',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='data',
        ),
        migrations.AddField(
            model_name='routine',
            name='bgImage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='doneAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='MyTraining',
        ),
        migrations.AddField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.Routine'),
        ),
        migrations.AddField(
            model_name='training',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='api.Workout'),
        ),
        migrations.AddField(
            model_name='set',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.Training'),
        ),
    ]
