# Generated by Django 3.0.8 on 2020-09-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200922_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=20),
        ),
    ]
