# Generated by Django 3.0.8 on 2020-09-26 10:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200923_1211'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='professor',
            managers=[
                ('objects', api.models.ProfessorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', api.models.StudentManager()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_code',
        ),
        migrations.AddField(
            model_name='professor',
            name='professor_code',
            field=models.CharField(default='P', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
