# Generated by Django 3.0.8 on 2020-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200926_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_code',
            field=models.CharField(max_length=20, verbose_name='교수번호'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_major',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='professor_name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=20, verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
    ]
