# Generated by Django 3.0.8 on 2020-12-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_routine_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='bgImage',
            new_name='bg_image',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='doneAt',
            new_name='done_at',
        ),
    ]
